// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: COMMObj.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "COMMObj.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace COMMObj {

namespace {

const ::google::protobuf::Descriptor* COMMObj_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  COMMObj_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_COMMObj_2eproto() {
  protobuf_AddDesc_COMMObj_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "COMMObj.proto");
  GOOGLE_CHECK(file != NULL);
  COMMObj_descriptor_ = file->message_type(0);
  static const int COMMObj_offsets_[9] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(COMMObj, operate_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(COMMObj, username_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(COMMObj, tab_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(COMMObj, site_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(COMMObj, byte_data_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(COMMObj, field_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(COMMObj, row_begin_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(COMMObj, row_size_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(COMMObj, type_),
  };
  COMMObj_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      COMMObj_descriptor_,
      COMMObj::default_instance_,
      COMMObj_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(COMMObj, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(COMMObj, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(COMMObj));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_COMMObj_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    COMMObj_descriptor_, &COMMObj::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_COMMObj_2eproto() {
  delete COMMObj::default_instance_;
  delete COMMObj_reflection_;
  delete COMMObj::_default_type_;
}

void protobuf_AddDesc_COMMObj_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\rCOMMObj.proto\022\007COMMObj\"\263\001\n\007COMMObj\022\017\n\007"
    "operate\030\001 \002(\t\022\020\n\010username\030\002 \002(\t\022\020\n\010tab_n"
    "ame\030\003 \002(\t\022\014\n\004site\030\004 \002(\t\022\021\n\tbyte_data\030\005 \002"
    "(\t\022\022\n\nfield_name\030\006 \003(\t\022\025\n\trow_begin\030\007 \001("
    "\005:\002-1\022\024\n\010row_size\030\010 \001(\005:\002-1\022\021\n\004type\030\t \001("
    "\t:\003obj", 206);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "COMMObj.proto", &protobuf_RegisterTypes);
  COMMObj::_default_type_ =
      new ::std::string("obj", 3);
  COMMObj::default_instance_ = new COMMObj();
  COMMObj::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_COMMObj_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_COMMObj_2eproto {
  StaticDescriptorInitializer_COMMObj_2eproto() {
    protobuf_AddDesc_COMMObj_2eproto();
  }
} static_descriptor_initializer_COMMObj_2eproto_;

// ===================================================================

::std::string* COMMObj::_default_type_ = NULL;
#ifndef _MSC_VER
const int COMMObj::kOperateFieldNumber;
const int COMMObj::kUsernameFieldNumber;
const int COMMObj::kTabNameFieldNumber;
const int COMMObj::kSiteFieldNumber;
const int COMMObj::kByteDataFieldNumber;
const int COMMObj::kFieldNameFieldNumber;
const int COMMObj::kRowBeginFieldNumber;
const int COMMObj::kRowSizeFieldNumber;
const int COMMObj::kTypeFieldNumber;
#endif  // !_MSC_VER

COMMObj::COMMObj()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void COMMObj::InitAsDefaultInstance() {
}

COMMObj::COMMObj(const COMMObj& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void COMMObj::SharedCtor() {
  _cached_size_ = 0;
  operate_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  username_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  tab_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  site_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  byte_data_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  row_begin_ = -1;
  row_size_ = -1;
  type_ = const_cast< ::std::string*>(_default_type_);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

COMMObj::~COMMObj() {
  SharedDtor();
}

void COMMObj::SharedDtor() {
  if (operate_ != &::google::protobuf::internal::kEmptyString) {
    delete operate_;
  }
  if (username_ != &::google::protobuf::internal::kEmptyString) {
    delete username_;
  }
  if (tab_name_ != &::google::protobuf::internal::kEmptyString) {
    delete tab_name_;
  }
  if (site_ != &::google::protobuf::internal::kEmptyString) {
    delete site_;
  }
  if (byte_data_ != &::google::protobuf::internal::kEmptyString) {
    delete byte_data_;
  }
  if (type_ != _default_type_) {
    delete type_;
  }
  if (this != default_instance_) {
  }
}

void COMMObj::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* COMMObj::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return COMMObj_descriptor_;
}

const COMMObj& COMMObj::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_COMMObj_2eproto();
  return *default_instance_;
}

COMMObj* COMMObj::default_instance_ = NULL;

COMMObj* COMMObj::New() const {
  return new COMMObj;
}

void COMMObj::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_operate()) {
      if (operate_ != &::google::protobuf::internal::kEmptyString) {
        operate_->clear();
      }
    }
    if (has_username()) {
      if (username_ != &::google::protobuf::internal::kEmptyString) {
        username_->clear();
      }
    }
    if (has_tab_name()) {
      if (tab_name_ != &::google::protobuf::internal::kEmptyString) {
        tab_name_->clear();
      }
    }
    if (has_site()) {
      if (site_ != &::google::protobuf::internal::kEmptyString) {
        site_->clear();
      }
    }
    if (has_byte_data()) {
      if (byte_data_ != &::google::protobuf::internal::kEmptyString) {
        byte_data_->clear();
      }
    }
    row_begin_ = -1;
    row_size_ = -1;
  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (has_type()) {
      if (type_ != _default_type_) {
        type_->assign(*_default_type_);
      }
    }
  }
  field_name_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool COMMObj::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string operate = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_operate()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->operate().data(), this->operate().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_username;
        break;
      }

      // required string username = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_username:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_username()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->username().data(), this->username().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_tab_name;
        break;
      }

      // required string tab_name = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_tab_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_tab_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->tab_name().data(), this->tab_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_site;
        break;
      }

      // required string site = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_site:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_site()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->site().data(), this->site().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_byte_data;
        break;
      }

      // required string byte_data = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_byte_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_byte_data()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->byte_data().data(), this->byte_data().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(50)) goto parse_field_name;
        break;
      }

      // repeated string field_name = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_field_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_field_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->field_name(this->field_name_size() - 1).data(),
            this->field_name(this->field_name_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(50)) goto parse_field_name;
        if (input->ExpectTag(56)) goto parse_row_begin;
        break;
      }

      // optional int32 row_begin = 7 [default = -1];
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_row_begin:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &row_begin_)));
          set_has_row_begin();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(64)) goto parse_row_size;
        break;
      }

      // optional int32 row_size = 8 [default = -1];
      case 8: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_row_size:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &row_size_)));
          set_has_row_size();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(74)) goto parse_type;
        break;
      }

      // optional string type = 9 [default = "obj"];
      case 9: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_type:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_type()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->type().data(), this->type().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void COMMObj::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string operate = 1;
  if (has_operate()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->operate().data(), this->operate().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->operate(), output);
  }

  // required string username = 2;
  if (has_username()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->username().data(), this->username().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->username(), output);
  }

  // required string tab_name = 3;
  if (has_tab_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->tab_name().data(), this->tab_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->tab_name(), output);
  }

  // required string site = 4;
  if (has_site()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->site().data(), this->site().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      4, this->site(), output);
  }

  // required string byte_data = 5;
  if (has_byte_data()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->byte_data().data(), this->byte_data().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      5, this->byte_data(), output);
  }

  // repeated string field_name = 6;
  for (int i = 0; i < this->field_name_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->field_name(i).data(), this->field_name(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      6, this->field_name(i), output);
  }

  // optional int32 row_begin = 7 [default = -1];
  if (has_row_begin()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(7, this->row_begin(), output);
  }

  // optional int32 row_size = 8 [default = -1];
  if (has_row_size()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(8, this->row_size(), output);
  }

  // optional string type = 9 [default = "obj"];
  if (has_type()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->type().data(), this->type().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      9, this->type(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* COMMObj::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string operate = 1;
  if (has_operate()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->operate().data(), this->operate().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->operate(), target);
  }

  // required string username = 2;
  if (has_username()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->username().data(), this->username().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->username(), target);
  }

  // required string tab_name = 3;
  if (has_tab_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->tab_name().data(), this->tab_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->tab_name(), target);
  }

  // required string site = 4;
  if (has_site()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->site().data(), this->site().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->site(), target);
  }

  // required string byte_data = 5;
  if (has_byte_data()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->byte_data().data(), this->byte_data().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->byte_data(), target);
  }

  // repeated string field_name = 6;
  for (int i = 0; i < this->field_name_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->field_name(i).data(), this->field_name(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(6, this->field_name(i), target);
  }

  // optional int32 row_begin = 7 [default = -1];
  if (has_row_begin()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(7, this->row_begin(), target);
  }

  // optional int32 row_size = 8 [default = -1];
  if (has_row_size()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(8, this->row_size(), target);
  }

  // optional string type = 9 [default = "obj"];
  if (has_type()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->type().data(), this->type().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        9, this->type(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int COMMObj::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string operate = 1;
    if (has_operate()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->operate());
    }

    // required string username = 2;
    if (has_username()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->username());
    }

    // required string tab_name = 3;
    if (has_tab_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->tab_name());
    }

    // required string site = 4;
    if (has_site()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->site());
    }

    // required string byte_data = 5;
    if (has_byte_data()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->byte_data());
    }

    // optional int32 row_begin = 7 [default = -1];
    if (has_row_begin()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->row_begin());
    }

    // optional int32 row_size = 8 [default = -1];
    if (has_row_size()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->row_size());
    }

  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // optional string type = 9 [default = "obj"];
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->type());
    }

  }
  // repeated string field_name = 6;
  total_size += 1 * this->field_name_size();
  for (int i = 0; i < this->field_name_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->field_name(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void COMMObj::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const COMMObj* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const COMMObj*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void COMMObj::MergeFrom(const COMMObj& from) {
  GOOGLE_CHECK_NE(&from, this);
  field_name_.MergeFrom(from.field_name_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_operate()) {
      set_operate(from.operate());
    }
    if (from.has_username()) {
      set_username(from.username());
    }
    if (from.has_tab_name()) {
      set_tab_name(from.tab_name());
    }
    if (from.has_site()) {
      set_site(from.site());
    }
    if (from.has_byte_data()) {
      set_byte_data(from.byte_data());
    }
    if (from.has_row_begin()) {
      set_row_begin(from.row_begin());
    }
    if (from.has_row_size()) {
      set_row_size(from.row_size());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_type()) {
      set_type(from.type());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void COMMObj::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void COMMObj::CopyFrom(const COMMObj& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool COMMObj::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000001f) != 0x0000001f) return false;

  return true;
}

void COMMObj::Swap(COMMObj* other) {
  if (other != this) {
    std::swap(operate_, other->operate_);
    std::swap(username_, other->username_);
    std::swap(tab_name_, other->tab_name_);
    std::swap(site_, other->site_);
    std::swap(byte_data_, other->byte_data_);
    field_name_.Swap(&other->field_name_);
    std::swap(row_begin_, other->row_begin_);
    std::swap(row_size_, other->row_size_);
    std::swap(type_, other->type_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata COMMObj::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = COMMObj_descriptor_;
  metadata.reflection = COMMObj_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace COMMObj

// @@protoc_insertion_point(global_scope)
